<a href="https://colab.research.google.com/github/USMS-FPK-IA-GI-2025/controle-01-numpy-and-matplotlib-iris-Naj-add/blob/main/notebooks/controle_numpy_matplotlib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Contrôle 01 — Data Science avec NumPy et Matplotlib
**Master 1 — Intelligence Artificielle & Génie Informatique (FPK / USMS)**

Nom & Prénom : ADDA Najwa
Filière :  SIIA
Année universitaire : 2025 - 2026

---

**Règles :**
- Bibliothèques autorisées : NumPy, Matplotlib
- Toute autre bibliothèque est interdite
- Chaque question doit être traitée dans une cellule dédiée
- Chaque résultat doit être brièvement interprété


# Partie A — Importation du Dataset, Arrays, Premières Manipulations

### A1. Importation du dataset
Importez NumPy et Matplotlib.  
Chargez le fichier `iris.csv` avec `np.genfromtxt` (`delimiter=','`, `skip_header=1`).  
Stockez les données dans un array nommé `data` et affichez sa `shape`.


In [65]:
import numpy as np
import matplotlib.pyplot as plt
data = np.genfromtxt('Iris.csv' , delimiter=',' , skip_header=1, dtype= object)
print(data.shape)

(150, 6)


### A2. Séparation des features et des espèces
Séparez :
- les 4 premières colonnes numériques dans un array `features`
- la dernière colonne (espèces) dans un array `species`
Utilisez le slicing.


In [66]:
features = data[:,1:5].astype(float)
species = data[:,-1].astype(str)

### A3. Indexing
Affichez les 5 premières lignes de `features` en utilisant l’indexing.


In [67]:
print(features[:5])


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


### A4. Extraction d’une colonne
Créez un array `sepal_length` contenant uniquement la première colonne de `features`.  
Affichez sa `size` et son `dtype`.


In [68]:
sepal_length = features[:,0]
print(sepal_length.size)
print(sepal_length.dtype)

150
float64


### A5. Slicing par espèce
Utilisez le slicing pour extraire les 50 premières lignes correspondant à l’espèce *Setosa*.  
Stockez-les dans `setosa_features`.


In [69]:
setosa_features = features[:50]

# Partie B — Statistiques Basiques et Opérations Mathématiques

### B6. Moyenne par colonne
Calculez la moyenne de chaque colonne de `features` avec `np.mean(axis=0)`.


In [70]:
moyenne_colonne = np.mean(features, axis=0)
print(moyenne_colonne)

[5.84333333 3.054      3.75866667 1.19866667]


### B7. Min et Max
Trouvez la valeur minimale et maximale de la longueur des pétales.


In [71]:
min_petal_lengh = np.min(features[:, 2])
max_petal_lengh = np.max(features[:, 2])
print(min_petal_lengh)
print(max_petal_lengh)

1.0
6.9


### B9. Normalisation
Normalisez les longueurs des pétales en les divisant par leur maximum.
Stockez le résultat dans `normalized_petals`.


In [72]:
normalized_petals = features[:, 2] / max_petal_lengh

### B10. Somme cumulée
Calculez la somme cumulée des largeurs des pétales pour Versicolor.
Affichez les 10 premières valeurs.


In [73]:
somme_cumulee = np.cumsum(features[50:100, 3])
print(somme_cumulee[:10])


[ 1.4  2.9  4.4  5.7  7.2  8.5 10.1 11.1 12.4 13.8]


### B10. Somme cumulée
Calculez la somme cumulée des largeurs des pétales pour Versicolor.
Affichez les 10 premières valeurs.


In [74]:
somme_cumulee = np.cumsum(features[50:100, 3])
print(somme_cumulee[:10])

[ 1.4  2.9  4.4  5.7  7.2  8.5 10.1 11.1 12.4 13.8]


# Partie C — Transformations Avancées avec NumPy

### C11. Espèces uniques
Listez les espèces uniques avec `np.unique` et comptez leurs occurrences.


In [75]:
unique_species, count = np.unique(species , return_counts=True)
print(unique_species)
print(count)

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']
[50 50 50]


### C12. Reshape par espèce
Transformez `features` en un array de forme `(3, 50, 4)` nommé `features_by_species`.


In [76]:
features_by_species = features.reshape((3, 50, 4))

### C13. Concaténation
Concaténez horizontalement les moyennes par colonne avec un array de zéros.


In [77]:
np.concatenate((moyenne_colonne, np.zeros(1)), axis=0)

array([5.84333333, 3.054     , 3.75866667, 1.19866667, 0.        ])

### C14. Data cleaning (simulation)
Simulez des valeurs NaN et remplacez-les avec `np.nan_to_num`.


In [78]:
NaN = np.nan_to_num(features)

### C15. Broadcasting
Ajoutez 1 à toutes les valeurs de la première colonne de `features`.


In [79]:
features[:, 0] = features[:, 0] + 1
print(features[:, 0])

[6.1 5.9 5.7 5.6 6.  6.4 5.6 6.  5.4 5.9 6.4 5.8 5.8 5.3 6.8 6.7 6.4 6.1
 6.7 6.1 6.4 6.1 5.6 6.1 5.8 6.  6.  6.2 6.2 5.7 5.8 6.4 6.2 6.5 5.9 6.
 6.5 5.9 5.4 6.1 6.  5.5 5.4 6.  6.1 5.8 6.1 5.6 6.3 6.  8.  7.4 7.9 6.5
 7.5 6.7 7.3 5.9 7.6 6.2 6.  6.9 7.  7.1 6.6 7.7 6.6 6.8 7.2 6.6 6.9 7.1
 7.3 7.1 7.4 7.6 7.8 7.7 7.  6.7 6.5 6.5 6.8 7.  6.4 7.  7.7 7.3 6.6 6.5
 6.5 7.1 6.8 6.  6.6 6.7 6.7 7.2 6.1 6.7 7.3 6.8 8.1 7.3 7.5 8.6 5.9 8.3
 7.7 8.2 7.5 7.4 7.8 6.7 6.8 7.4 7.5 8.7 8.7 7.  7.9 6.6 8.7 7.3 7.7 8.2
 7.2 7.1 7.4 8.2 8.4 8.9 7.4 7.3 7.1 8.7 7.3 7.4 7.  7.9 7.7 7.9 6.8 7.8
 7.7 7.7 7.3 7.5 7.2 6.9]


### C16. np.where
Créez un array binaire indiquant si la longueur des pétales est supérieure à 4.0.


In [96]:
# 0 = faux et 1 = vrai
array_binaire = (features[:, 2] > 4.0).astype(int)
print(array_binaire)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 1 1 0 1 0 0 1 0 1 0 1 1 1 1 0 1 0 1 1
 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 0 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1]


# Partie D — Visualisation avec Matplotlib (Plots Simples)

### D17. Line plot
Line plot des longueurs des sépales pour les 50 premières fleurs.


### D18. Scatter plot
Scatter plot : longueur vs largeur des pétales.


In [82]:
# Votre code ici


### D19. Bar chart
Bar chart des moyennes des quatre caractéristiques.


In [83]:
# Votre code ici


### D20. Histogram
Histogramme de la largeur des sépales (10 bins).


In [84]:
# Votre code ici


### D21. Boxplot par espèce
Boxplot des longueurs des pétales par espèce.


In [85]:
# Votre code ici


# Partie E — Visualisations Avancées

### E22. Subplots comparatifs
Deux scatter plots côte à côte : Setosa vs Versicolor.


In [86]:
# Votre code ici


### E23. Grille 2x2
Histogrammes des 4 caractéristiques avec `plt.subplots(2,2)`.


In [87]:
# Votre code ici


### E24. Bar chart avec error bars
Moyennes par espèce avec écart-type.


In [88]:
# Votre code ici


### E25. Scatter coloré par espèce
Scatter plot avec couleurs par espèce.


In [89]:
# Votre code ici


### E26. Line plot superposé
Cumsum des largeurs des pétales par espèce.


In [90]:
# Votre code ici


# Partie F — Mini-Analyse Finale

### F27. Corrélations
Calculez la matrice de corrélation avec `np.corrcoef`.


In [91]:
# Votre code ici


### F28. Visualisation des corrélations
Visualisez les corrélations sous forme de bar chart ou scatter.


In [92]:
# Votre code ici


### F29. Variance par espèce
Identifiez l’espèce avec la plus grande variance globale et visualisez ses distributions.


In [93]:
# Votre code ici


### F30. Conclusion
Rédigez une conclusion contenant **3 insights** issus de votre analyse.


1) ...
2) ...
3) ...